# Generated by Django 4.0.2 on 2022-02-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PetOwnerMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet_website.owner')),
                ('petid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet_website.pet')),
            ],
        ),
    ]
