# Generated by Django 4.0.2 on 2022-02-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
